import Providers from "@/components/providers";
import { inter } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("flex min-h-dvh flex-col antialiased", inter.className)}
      >
        <Providers>
          <main className="container mx-auto flex-1 px-4 font-light sm:px-6 md:px-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
